id: A2EC1EB65
title: Prayer to the Lineage of Lumorab
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:02:24.677084
  last_modified_at: 2022-03-01 02:02:24.677111
